language: php

services:
    - mysql

php:
    - 7.2

install:
    - composer install --dev

before_script:
    - mkdir var/cache -p
    - chmod 777 -R var/cache

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
