---
- hosts: all

  tasks:
       - import_tasks: ../tasks/deploy/init.yml
       - import_tasks: ../tasks/deploy/git.yml
       - import_tasks: ../tasks/deploy/symfony.init.yml
       - import_tasks: ../tasks/deploy/shared.yml
       - import_tasks: ../tasks/deploy/composer.yml
       - import_tasks: ../tasks/deploy/symfony.yml
       - import_tasks: ../tasks/deploy/optimize-assets.yml
       - import_tasks: ../tasks/deploy/finalize.yml
