- name: Clear the Symfony cache
  shell: '{{ deploy_helper.new_release_path }}/bin/console cache:clear --env=prod'

- name: Warmup the Symfony cache
  shell: '{{ deploy_helper.new_release_path }}/bin/console cache:warmup --env=prod'

- name: Set the permissions for the Symfony cache directory
  file:
    path: '{{ item }}'
    state: directory
    group: www-data
    recurse: yes
  with_items:
    - '{{ deploy_helper.new_release_path }}/var'
    - '{{ deploy_helper.new_release_path }}/web/media/cache/'

- name: Remove the app_dev.php and app_test.php
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ deploy_helper.new_release_path }}/web/app_dev.php'
    - '{{ deploy_helper.new_release_path }}/web/app_test.php'

- name: Ensure the media cache directory is created
  file:
    path: '{{ deploy_helper.new_release_path }}/web/media/cache'
    state: directory
    group: www-data
