services:
    ### Registry ###
    JK\DeployBundle\Module\Registry\ModuleRegistry:
        class: JK\DeployBundle\Module\Registry\ModuleRegistry
        public: true

    ### Modules ###
    JK\DeployBundle\Module\Modules\DatabaseModule:
        class: JK\DeployBundle\Module\Modules\DatabaseModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\PlaybookModule:
        class: JK\DeployBundle\Module\Modules\PlaybookModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\DeployModule:
        class: JK\DeployBundle\Module\Modules\DeployModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\GitModule:
        class: JK\DeployBundle\Module\Modules\GitModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\ComposerModule:
        class: JK\DeployBundle\Module\Modules\ComposerModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\FrameworkModule:
        class: JK\DeployBundle\Module\Modules\FrameworkModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\MakefileModule:
        class: JK\DeployBundle\Module\Modules\MakefileModule
        tags:
            - {name: deploy.module}

    JK\DeployBundle\Module\Modules\HostModule:
        class: JK\DeployBundle\Module\Modules\HostModule
        tags:
            - {name: deploy.module}

    ### Cache ###
    JK\DeployBundle\Cache\Cache:
        class: JK\DeployBundle\Cache\Cache
        arguments:
            - '%kernel.cache_dir%'
        public: true
