###> deploy ###
{{ env }}@install:
	ansible-playbook {{ prefix }}/playbooks/install.yaml -i {{ prefix }}/hosts/{{ env }}.yaml

{{ env }}@install.validate:
	ansible-playbook {{ prefix }}/playbooks/install.yaml -i {{ prefix }}/hosts/{{ env }}.yaml --check --diff

{{ env }}@deploy:
	ansible-playbook {{ prefix }}/playbooks/deploy.yaml -i {{ prefix }}/hosts/{{ env }}.yaml

{{ env }}@deploy.validate:
	ansible-playbook {{ prefix }}/playbooks/deploy.yaml -i {{ prefix }}/hosts/{{ env }}.yaml --check --diff

{{ env }}@rollback:
	ansible-playbook {{ prefix }}/playbooks/rollback.yaml -i {{ prefix }}/hosts/{{ env }}.yaml --check --diff

{{ env }}@rollback.validate:
	ansible-playbook {{ prefix }}/playbooks/rollback.yaml -i {{ prefix }}/hosts/{{ env }}.yaml --check --diff
###< deploy ###
